---Tìm cư dân chưa có xe
SELECT CD.TenCuDan
FROM CuDan CD
LEFT JOIN XeMay XM ON CD.IDCuDan = XM.IDCuDan
LEFT JOIN XeOTo XO ON CD.IDCuDan = XO.IDCuDan
LEFT JOIN XeDap XD ON CD.IDCuDan = XD.IDCuDan
WHERE XM.IDXeMay IS NULL 
  AND XO.IDXeOTo IS NULL 
  AND XD.IDXeDap IS NULL;
